export type CategoryGroup = "ESSENTIAL" | "LIFESTYLE" | "FINANCIAL" | "INCOME" | "OTHER";

export type Category =
  | "HOUSING"
  | "UTILITIES"
  | "GROCERIES"
  | "TRANSPORTATION"
  | "INSURANCE"
  | "HEALTHCARE"
  | "CHILDCARE"
  | "DINING"
  | "ENTERTAINMENT"
  | "SHOPPING"
  | "TRAVEL"
  | "PERSONAL_CARE"
  | "SUBSCRIPTIONS"
  | "SAVINGS"
  | "INVESTMENTS"
  | "DEBT_PAYMENT"
  | "FEES"
  | "SALARY"
  | "INVESTMENT_INCOME"
  | "OTHER_INCOME"
  | "TRANSFER"
  | "UNCATEGORIZED";

export const CATEGORY_GROUP: Record<Category, CategoryGroup> = {
  HOUSING: "ESSENTIAL",
  UTILITIES: "ESSENTIAL",
  GROCERIES: "ESSENTIAL",
  TRANSPORTATION: "ESSENTIAL",
  INSURANCE: "ESSENTIAL",
  HEALTHCARE: "ESSENTIAL",
  CHILDCARE: "ESSENTIAL",
  DINING: "LIFESTYLE",
  ENTERTAINMENT: "LIFESTYLE",
  SHOPPING: "LIFESTYLE",
  TRAVEL: "LIFESTYLE",
  PERSONAL_CARE: "LIFESTYLE",
  SUBSCRIPTIONS: "LIFESTYLE",
  SAVINGS: "FINANCIAL",
  INVESTMENTS: "FINANCIAL",
  DEBT_PAYMENT: "FINANCIAL",
  FEES: "FINANCIAL",
  SALARY: "INCOME",
  INVESTMENT_INCOME: "INCOME",
  OTHER_INCOME: "INCOME",
  TRANSFER: "OTHER",
  UNCATEGORIZED: "OTHER",
};
